# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: vs2017-win2016

steps:
- task: BuildSSIS@1
  inputs:
    solnPath: '$(Build.SourcesDirectory)/src/SQLStart2021.sln'
    solnConfigName: 'Development'
    projPath: '$(Build.SourcesDirectory)/src/SQLStart2021/SQLStart2021.dtproj'
    projConfigName: 'Development'
    cmdSwitch: 'rebuild'
    devenvVersion: 'hostedVS2017'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/SQLStart2021/bin/Development'
    Contents: '*.ispac'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/_SQLStart2021'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/_SQLStart2021'
    ArtifactName: 'SQLStartDrop'
    publishLocation: 'Container'